### ISSUE TITLE
Make Sidecar feature gate configurable

### ISSUE THREAD

**Issue by PendaGTP** [kubevirt/hyperconverged-cluster-operator#2033]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

/kind enhancement

**What happened**:

It is not possible to activate the sidecar feature gate.

**What you expected to happen**:

Allow to activate or not the sidecar gate feature.

**Comment by tiraboschi** [comment]
Hi,
Sidecar FG is not exposed anymore on HCO by design:
The sidecar hook mechanism is considered a serious security hole: it allows anyone to execute arbitrary third party code in the VMI pod but VMI pods are/can be executed with capabilities that a user may not actually have.
So it's basically a path for privilege escalation.

You can use `kubevirt.kubevirt.io/jsonpatch` annotation mechanism to enable experimental/unsupported feature gates on Kubevirt, see:
https://github.com/kubevirt/hyperconverged-cluster-operator/blob/main/docs/cluster-configuration.md#kubevirt-feature-gates

Closing this as won't fix.

**Comment by orenc1** [comment]
Just to complete the workaround suggestion, the way to add "Sidecar" feature gate into KubeVirt CR by HCO is:
`kubectl annotate --overwrite -n kubevirt-hyperconverged hco kubevirt-hyperconverged kubevirt.kubevirt.io/jsonpatch='[{"op": "add", "path": "/spec/configuration/developerConfiguration/featureGates/-", "value": "Sidecar" }]'`
