### ISSUE TITLE
How often is expected to update the HCO operator in operatorhub.io?

### ISSUE THREAD

**Issue by alosadagrande** [kubevirt/hyperconverged-cluster-operator#365]
I just started to deploy OKD 4.3 with KubeVirt community operator which is based in the HCO. However, currently the version in operatorhub.io is running KubeVirt 0.18.1 which is quite old. Note that today version 0.24 of KubeVirt has been released with some new features (pause/unpause, vnc fixes...)

My questions are: 
* how often is expected to update the KubeVirt community operator so my OKD KubeVirt installation can be updated (manually or automatically) ? 
* is there any other method to update an already deployed KubeVirt community operator in OKD?

Thanks

**Comment by slintes** [comment]
Ah, seems there was a misunderstanding in the community meeting, sorry.
So we are talking about operatorhub.io
AFAIK there is no HCO in operatorhub.io, but KubeVirt only. There we are behind with regards to versions, true.

@tiraboschi are there plans for a HCO release on operatorhub.io at all? Any other recommended way for an upstream HCO deployment?
 
If not, this issue can be moved to kv/kv I guess, in order to ask for an update of the standalone KubeVirt operator.

**Comment by tiraboschi** [comment]
Yes, we are working for that.
https://github.com/kubevirt/hyperconverged-cluster-operator/pull/333 is an enabling step

**Comment by alosadagrande** [comment]
Thanks for your comments.

Am I wrong or KubeVirt community operator actually uses the hyperconverged-cluster operator behind the scenes?

**Comment by slintes** [comment]
> Am I wrong or KubeVirt community operator actually uses the hyperconverged-cluster operator behind the scenes?

No, the current KubeVirt operator on operatorhub.io is not using HCO
