### ISSUE TITLE
change sriov-network-type to d/s value in converged

### ISSUE THREAD

**Issue by rthallisey** [kubevirt/hyperconverged-cluster-operator#39]
`deploy/converged/operator.yaml` should change to it's downstream value singe `converged` is downstream only.
```
        - name: SRIOV_NETWORK_TYPE
          value: sriov
```

**Comment by booxter** [comment]
@rthallisey I am confused now. Here in the issue you are saying that `converged/operator.yaml` is downstream only (meaning, to be used when deploying on top of OCP?) while in https://github.com/kubevirt/hyperconverged-cluster-operator/pull/41#discussion_r278048417 Petr says that it's generic manifest (?) and so we shouldn't touch it.

On the other hand, evidently when I apply manifests from `converged` on OCP using default manifests I still get e.g. `bridge` CNI not `cnv-bridge` so is the manifest really for downstream then?

Please clarify because right now I am not even sure what this issue is supposed to tackle. Thanks.

**Comment by rthallisey** [comment]
>Not sure that is true. Converged is simply one big CSV for all components, should work on both U/S and D/S. Standard it the other "mode", where you deploy all components using their own CSVs. Not sure if it is used anywhere.
>
Converged is only going to be used d/s (released Openshift only) and checked into upstream git.  For upstream deployments (k8s or master branch of Openshift), we're going to use the 'standard' manifest.

The issue has to do with `SRIOV_NETWORK_TYPE` needing a different value d/s, so the downstream yaml (converged) needs the correct value.  I'm assuming this is still the expected behavior @phoracek?

**Comment by rthallisey** [comment]
@tiraboschi @irosenzw this should be covered by the work you're doing.

**Comment by phoracek** [comment]
@rthallisey with OpenShift's sriov-operator it is likely that we won't handle SR-IOV in HCO at all. It still need to be discussed though.

**Comment by phoracek** [comment]
SR-IOV is no longer part of Network Addons Operator. We can close this issue.
